### ISSUE TITLE
Docker build fails due to case sensitive file system

### ISSUE THREAD

**Issue by MJDrgn** [OhMyGuus/BetterCrewLink-server#13]
Attempting to compile on Ubuntu 20.04 ARM:

src/index.ts(11,29): error TS2307: Cannot find module './interfaces/publicLobby' or its corresponding type declarations.
src/index.ts(12,27): error TS2307: Cannot find module './interfaces/gameState' or its corresponding type declarations.
src/index.ts(13,27): error TS2307: Cannot find module './interfaces/lobbyInfo' or its corresponding type declarations.

This is fixed by renaming src/Interfaces to src/interfaces - changing the "i" to a lowercase. Compilation then succeeds as expected.

I think this has been tested/built on a Windows platform or a Linux platform with a case insensitive file system (like WSL).

**Comment by OhMyGuus** [comment]
Oh thanks for the report. Yeah It happened because git on Windows doesn't detect changes in the capitalization of files/folders.
